services:
  - type: web
    name: agri-backend
    runtime: docker
    dockerContext: ./server_backend
    dockerfilePath: server_backend/Dockerfile
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: "https://agri-frontend-g40p.onrender.com"
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_CONNECTION_STRING
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: HF_TOKEN
        sync: false